<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Zakira.Retrace.Core</RootNamespace>
    <AssemblyName>Zakira.Retrace.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zakira.Retrace.Abstractions\Zakira.Retrace.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zakira.Retrace.Core.UnitTests" />
    <InternalsVisibleTo Include="Zakira.Retrace.Sources.UnitTests" />
  </ItemGroup>

</Project>
